import React, {useMemo, useState, useEffect} from 'react';
import { createRoot } from 'react-dom/client';
import { Calculator, Database, FileText, AlertTriangle, PackageCheck, Download, Plus, Trash2, Beaker, LayoutDashboard, Search, RotateCcw, Layers, Upload } from 'lucide-react';
import './style.css';

const SOURCES = ['Meus','Nutrimenu','TACO','USDA','IBGE'];
const NUTRIENTS = [
  ['kcal','kcal'], ['kj','kJ'], ['carb','Carboidratos g'], ['sugars','Açúcares totais g'], ['addedSugars','Açúcares adicionados g'], ['protein','Proteínas g'], ['fat','Gorduras totais g'], ['satFat','Gorduras saturadas g'], ['transFat','Gorduras trans g'], ['fiber','Fibra alimentar g'], ['sodium','Sódio mg']
];
const baseRows = [
 ['Água','Base','Meus',0,0,0,0,0,0,0,0,0,0,0,'Valor padrão'],
 ['Açúcar cristal','Açúcar','Meus',400,1674,100,100,100,0,0,0,0,0,0,'Ajustar conforme fornecedor'],
 ['Glicose líquida','Açúcar','Meus',300,1255,75,35,75,0,0,0,0,0,0,'Xarope ~75% sólidos; ajustar DE/fornecedor'],
 ['Maltodextrina DE20','Sólidos','Meus',380,1590,95,5,95,0,0,0,0,0,0,'Ajustar ficha técnica'],
 ['Leite em pó desnatado','Lácteo','Meus',360,1506,52,52,0,36,1,0.6,0,0,500,'Exemplo; substituir por ficha técnica'],
 ['Leite em pó integral','Lácteo','Meus',496,2075,38,38,0,26,26,16,0,0,370,'Exemplo; substituir por ficha técnica'],
 ['Soro de leite desmineralizado','Lácteo','Meus',350,1464,74,74,0,12,1,0.6,0,0,600,'Exemplo; substituir por ficha técnica'],
 ['Gordura vegetal','Gordura','Meus',900,3766,0,0,0,0,100,45,0,0,0,'Ajustar perfil saturadas/trans conforme fornecedor'],
 ['Fibra de mandioca','Fibra','Meus',180,753,20,0,0,0,0,0,0,80,20,'Exemplo; substituir por ficha técnica'],
 ['Estabilizante Cryocap 3972','Estabilizante','Meus',250,1046,60,0,0,0,0,0,0,30,500,'Exemplo; substituir por ficha técnica'],
 ['Doce de leite recheio','Recheio','Meus',320,1339,58,55,35,7,8,5,0,0,120,'Exemplo para simulação'],
 ['Maltitol','Poliol','Meus',240,1004,99,0,0,0,0,0,0,0,0,'Poliol; confirmar ficha técnica'],
 ['Eritritol','Poliol','Meus',0,0,100,0,0,0,0,0,0,0,0,'Poliol; confirmar ficha técnica'],
 ['Xilitol','Poliol','Meus',240,1004,100,0,0,0,0,0,0,0,0,'Poliol; confirmar ficha técnica'],
 ['Sorbitol','Poliol','Meus',260,1088,100,0,0,0,0,0,0,0,0,'Poliol; confirmar ficha técnica'],
 ['Morango cru','Fruta','TACO',30,126,6.8,4.9,0,0.9,0.3,0,0,1.7,0,'Pré-cadastro para busca; revisar tabela oficial'],
 ['Banana prata crua','Fruta','TACO',98,410,26,15,0,1.3,0.1,0,0,2,0,'Pré-cadastro para busca; revisar tabela oficial'],
 ['Manga Tommy crua','Fruta','TACO',51,213,12.8,12,0,0.9,0.2,0,0,2.1,0,'Pré-cadastro para busca; revisar tabela oficial'],
 ['Cacau em pó alcalino 10/12','Cacau','Meus',320,1339,20,1,0,20,11,7,0,33,50,'Fornecedor'],
 ['Cacau em pó','Cacau','USDA',228,954,58,1.8,0,19.6,13.7,8.1,0,37,21,'Pré-cadastro para busca; revisar origem/umidade'],
 ['Leite integral','Lácteo','IBGE',61,255,4.8,4.8,0,3.2,3.3,2.1,0,0,43,'Pré-cadastro para busca; revisar tabela usada'],
 ['Creme de leite 25%','Lácteo','Meus',270,1130,4,4,0,2.5,25,16,0,0,55,'Fornecedor'],
 ['Óleo de girassol','Óleo','Meus',900,3766,0,0,0,0,100,10,0,0,0,'Fornecedor'],
 ['Óleo de algodão','Óleo','Meus',900,3766,0,0,0,0,100,26,0,0,0,'Fornecedor']
];
const defaultIngredients = baseRows.map(r=>({name:r[0], category:r[1], source:r[2], kcal:r[3], kj:r[4], carb:r[5], sugars:r[6], addedSugars:r[7], protein:r[8], fat:r[9], satFat:r[10], transFat:r[11], fiber:r[12], sodium:r[13], note:r[14]}));
const defaultCalda = [ ['Água',597],['Fibra de mandioca',8],['Maltodextrina DE20',33],['Leite em pó desnatado',67],['Soro de leite desmineralizado',17],['Estabilizante Cryocap 3972',6],['Gordura vegetal',72],['Glicose líquida',33],['Açúcar cristal',167] ].map(([ingredient, grams])=>({ingredient, grams}));
const defaultRecheio = [['Doce de leite recheio',1000]].map(([ingredient, grams])=>({ingredient, grams}));
const defaultAssembly = [ ['Calda Base','CALDA',85], ['Recheio','RECHEIO',15] ].map(([component,type,percent])=>({component,type,percent}));
const limits = {addedSugars:15, satFat:6, sodium:600};
function n(v){return Number(v)||0} function fmt(v,d=1){return (Number(v)||0).toLocaleString('pt-BR',{maximumFractionDigits:d,minimumFractionDigits:d})}
function calcFormula(rows, ingredients){ const total = rows.reduce((a,r)=>a+n(r.grams),0)||1; const out={}; NUTRIENTS.forEach(([k])=>out[k]=0); rows.forEach(r=>{const ing=ingredients.find(i=>i.name===r.ingredient); if(!ing)return; NUTRIENTS.forEach(([k])=>out[k]+=n(r.grams)*n(ing[k])/total)}); return {...out,totalGrams:total};}
function rowFinal(comp, calda, recheio, ingredients){ let source={}; if(comp.type==='CALDA')source=calda; else if(comp.type==='RECHEIO')source=recheio; else source=ingredients.find(i=>i.name===comp.component)||{}; const out={}; NUTRIENTS.forEach(([k])=>out[k]=n(source[k])*n(comp.percent)/100); return out; }
function calcFinal(assembly, calda, recheio, ingredients){ const out={}; NUTRIENTS.forEach(([k])=>out[k]=0); assembly.forEach(c=>{const r=rowFinal(c,calda,recheio,ingredients); NUTRIENTS.forEach(([k])=>out[k]+=r[k])}); return out;}
function vd(k,v){ const map={kcal:2000,carb:300,addedSugars:50,protein:50,fat:65,satFat:20,fiber:25,sodium:2000}; return map[k] ? v/map[k]*100 : null;}
function roundLabel(k,v){ if(k==='kcal'||k==='kj'||k==='sodium') return Math.round(v); if(v===0) return 0; return Math.round(v*10)/10;}
function App(){
 const [tab,setTab]=useState('dashboard'); const [ingredients,setIngredients]=useState(()=>JSON.parse(localStorage.getItem('ingredientesSorveteV2')||'null')||defaultIngredients); const [calda,setCalda]=useState(defaultCalda); const [recheio,setRecheio]=useState(defaultRecheio); const [assembly,setAssembly]=useState(defaultAssembly); const [product,setProduct]=useState('Sorvete exemplo'); const [portion,setPortion]=useState(60); const [house,setHouse]=useState('1 unidade / bola'); const [pack,setPack]=useState(16); const [q,setQ]=useState(''); const [activeSources,setActiveSources]=useState(SOURCES);
 useEffect(()=>localStorage.setItem('ingredientesSorveteV2',JSON.stringify(ingredients)),[ingredients]);
 const visibleIngredients=useMemo(()=>ingredients.filter(i=>activeSources.includes(i.source)),[ingredients,activeSources]);
 const caldaCalc=useMemo(()=>calcFormula(calda,ingredients),[calda,ingredients]); const recheioCalc=useMemo(()=>calcFormula(recheio,ingredients),[recheio,ingredients]); const final=useMemo(()=>calcFinal(assembly,caldaCalc,recheioCalc,ingredients),[assembly,caldaCalc,recheioCalc,ingredients]); const sumPct=assembly.reduce((a,r)=>a+n(r.percent),0);
 const warnings=[final.addedSugars>=limits.addedSugars?'ALTO EM AÇÚCAR ADICIONADO':null, final.satFat>=limits.satFat?'ALTO EM GORDURA SATURADA':null, final.sodium>=limits.sodium?'ALTO EM SÓDIO':null].filter(Boolean);
 const exportJson=()=>{const blob=new Blob([JSON.stringify({ingredients,calda,recheio,assembly,product,portion,house,pack},null,2)],{type:'application/json'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gelato-lab-dados.json';a.click()}
 const importCsv=(e)=>{const file=e.target.files?.[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{const lines=String(reader.result).split(/\r?\n/).filter(Boolean); const header=lines.shift().split(';').map(h=>h.trim()); const rows=lines.map(line=>{const cols=line.split(';'); const obj={}; header.forEach((h,i)=>obj[h]=cols[i]); return obj}); const mapped=rows.map(r=>({name:r.name||r.nome||'Ingrediente',category:r.category||r.categoria||'Importado',source:r.source||r.fonte||'Meus',note:r.note||r.obs||'',...Object.fromEntries(NUTRIENTS.map(([k])=>[k,n(r[k])]))})); setIngredients([...ingredients,...mapped]);}; reader.readAsText(file,'utf-8')}
 return <div className="app"><aside><div className="brand"><Beaker/> <div><b>Gelato Lab</b><small>Nutrição • FT • Rótulo</small></div></div>{[['dashboard',LayoutDashboard,'Painel'],['ingredientes',Database,'Ingredientes'],['componentes',Calculator,'Calda/Recheio'],['montagem',PackageCheck,'Montagem final'],['rotulo',FileText,'Rótulo e FT'],['alertas',AlertTriangle,'Alertas ANVISA']].map(([id,Icon,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={18}/>{label}</button>)}<button onClick={exportJson}><Download size={18}/>Exportar dados</button><button onClick={()=>{localStorage.removeItem('ingredientesSorveteV2'); location.reload()}}><RotateCcw size={18}/>Restaurar base</button></aside><main><header><div><h1>{tab==='dashboard'?'Painel principal':tab==='rotulo'?'Rótulo e ficha técnica':tab==='componentes'?'Componentes intermediários':tab==='montagem'?'Montagem do produto final':tab==='alertas'?'Alertas regulatórios':'Banco de ingredientes'}</h1><p>Busca por ingrediente com seleção por fonte: Meus, Nutrimenu, TACO, USDA e IBGE.</p></div><div className="status"><span className={Math.abs(sumPct-100)<.01?'ok':'bad'}>{fmt(sumPct,2)}% composição</span>{warnings.length?<span className="warn">{warnings.length} lupa(s)</span>:<span className="ok">Sem lupa</span>}</div></header>{tab==='dashboard'&&<Dashboard final={final} warnings={warnings} product={product} setProduct={setProduct} portion={portion} setPortion={setPortion} house={house} setHouse={setHouse} pack={pack} setPack={setPack} ingredients={ingredients}/>} {tab==='ingredientes'&&<Ingredients ingredients={ingredients} setIngredients={setIngredients} q={q} setQ={setQ} activeSources={activeSources} setActiveSources={setActiveSources} importCsv={importCsv}/>} {tab==='componentes'&&<Components ingredients={visibleIngredients} calda={calda} setCalda={setCalda} recheio={recheio} setRecheio={setRecheio} caldaCalc={caldaCalc} recheioCalc={recheioCalc}/>} {tab==='montagem'&&<Assembly assembly={assembly} setAssembly={setAssembly} ingredients={visibleIngredients} caldaCalc={caldaCalc} recheioCalc={recheioCalc} final={final}/>} {tab==='rotulo'&&<Label product={product} portion={portion} house={house} pack={pack} final={final} warnings={warnings}/>} {tab==='alertas'&&<Alerts final={final}/>}</main></div>}
function Dashboard(p){return <><section className="cards"><div className="card"><small>Ingredientes cadastrados</small><strong>{p.ingredients.length}</strong><span>itens</span></div>{[['Valor energético',p.final.kcal,'kcal'],['Carboidratos',p.final.carb,'g'],['Açúcares adicionados',p.final.addedSugars,'g'],['Sódio',p.final.sodium,'mg']].map(x=><div className="card"><small>{x[0]} / 100 g</small><strong>{fmt(x[1],x[2]==='mg'?0:1)}</strong><span>{x[2]}</span></div>)}</section><section className="panel grid2"><div><h2>Dados do produto</h2><Input label="Nome do produto" value={p.product} onChange={p.setProduct}/><Input label="Porção (g)" value={p.portion} onChange={p.setPortion} type="number"/><Input label="Medida caseira" value={p.house} onChange={p.setHouse}/><Input label="Porções por embalagem" value={p.pack} onChange={p.setPack} type="number"/></div><div><h2>Resultado regulatório</h2>{p.warnings.length?p.warnings.map(w=><div className="lupa">{w}</div>):<div className="success">Não atingiu limites para rotulagem nutricional frontal nos parâmetros avaliados.</div>}<p className="note">A base já aceita múltiplas fontes e importação CSV separada por ponto e vírgula.</p></div></section></>}
function SourceFilters({activeSources,setActiveSources}){return <div className="sourcebar"><Layers size={18}/>{SOURCES.map(s=><label className={'chip '+s.toLowerCase()}><input type="checkbox" checked={activeSources.includes(s)} onChange={e=>setActiveSources(e.target.checked?[...activeSources,s]:activeSources.filter(x=>x!==s))}/>{s}</label>)}</div>}
function Ingredients({ingredients,setIngredients,q,setQ,activeSources,setActiveSources,importCsv}){const list=ingredients.filter(i=>activeSources.includes(i.source)&&(i.name.toLowerCase().includes(q.toLowerCase())||i.category.toLowerCase().includes(q.toLowerCase())||i.source.toLowerCase().includes(q.toLowerCase()))); const upd=(idx,k,v)=>setIngredients(ingredients.map((it,i)=>i===idx?{...it,[k]:['name','category','source','note'].includes(k)?v:n(v)}:it)); return <section className="panel"><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Digite o ingrediente: leite, cacau, morango..." value={q} onChange={e=>setQ(e.target.value)}/></div><label className="primary filebtn"><Upload size={16}/>Importar CSV<input type="file" accept=".csv,.txt" onChange={importCsv}/></label><button className="primary" onClick={()=>setIngredients([...ingredients,{name:'Novo ingrediente',category:'Categoria',source:'Meus',kcal:0,kj:0,carb:0,sugars:0,addedSugars:0,protein:0,fat:0,satFat:0,transFat:0,fiber:0,sodium:0,note:''}])}><Plus size={16}/>Adicionar</button></div><SourceFilters activeSources={activeSources} setActiveSources={setActiveSources}/><div className="tablewrap"><table><thead><tr><th>Ingrediente</th><th>Fonte</th><th>Categoria</th>{NUTRIENTS.map(n=><th>{n[1]}</th>)}<th>Obs.</th><th></th></tr></thead><tbody>{list.map((ing)=>{const idx=ingredients.indexOf(ing); return <tr><td><input value={ing.name} onChange={e=>upd(idx,'name',e.target.value)}/></td><td><select value={ing.source} onChange={e=>upd(idx,'source',e.target.value)}>{SOURCES.map(s=><option>{s}</option>)}</select></td><td><input value={ing.category} onChange={e=>upd(idx,'category',e.target.value)}/></td>{NUTRIENTS.map(([k])=><td><input type="number" value={ing[k]} onChange={e=>upd(idx,k,e.target.value)}/></td>)}<td><input value={ing.note} onChange={e=>upd(idx,'note',e.target.value)}/></td><td><button className="icon" onClick={()=>setIngredients(ingredients.filter((_,i)=>i!==idx))}><Trash2 size={16}/></button></td></tr>})}</tbody></table></div></section>}
function IngredientPicker({value,onChange,ingredients}){const id='ing-'+Math.random().toString(36).slice(2); return <><input list={id} value={value} onChange={e=>onChange(e.target.value)} placeholder="Digite para buscar..."/><datalist id={id}>{ingredients.map(x=><option value={x.name}>{x.source} • {x.category}</option>)}</datalist></>}
function RecipeTable({title,rows,setRows,ingredients,calc}){const upd=(i,k,v)=>setRows(rows.map((r,idx)=>idx===i?{...r,[k]:k==='grams'?n(v):v}:r)); return <section className="panel"><div className="toolbar"><h2>{title}</h2><button className="primary" onClick={()=>setRows([...rows,{ingredient:ingredients[0]?.name||'',grams:0}])}><Plus size={16}/>Linha</button></div><table><thead><tr><th>Ingrediente pesquisável</th><th>Quantidade g</th><th>kcal contrib.</th><th>Carb.</th><th>Aç. adic.</th><th>Gord.</th><th></th></tr></thead><tbody>{rows.map((r,i)=>{const ing=ingredients.find(x=>x.name===r.ingredient)||{}; return <tr><td><IngredientPicker value={r.ingredient} onChange={v=>upd(i,'ingredient',v)} ingredients={ingredients}/></td><td><input type="number" value={r.grams} onChange={e=>upd(i,'grams',e.target.value)}/></td><td>{fmt(n(r.grams)*n(ing.kcal)/100,1)}</td><td>{fmt(n(r.grams)*n(ing.carb)/100,1)}</td><td>{fmt(n(r.grams)*n(ing.addedSugars)/100,1)}</td><td>{fmt(n(r.grams)*n(ing.fat)/100,1)}</td><td><button className="icon" onClick={()=>setRows(rows.filter((_,idx)=>idx!==i))}><Trash2 size={16}/></button></td></tr>})}</tbody></table><div className="mini"><b>Total:</b> {fmt(calc.totalGrams,0)} g • <b>kcal/100g:</b> {fmt(calc.kcal,1)} • <b>Carb:</b> {fmt(calc.carb,1)} g • <b>Gord:</b> {fmt(calc.fat,1)} g</div></section>}
function Components(p){return <div className="stack"><RecipeTable title="Calda Base" rows={p.calda} setRows={p.setCalda} ingredients={p.ingredients} calc={p.caldaCalc}/><RecipeTable title="Recheio" rows={p.recheio} setRows={p.setRecheio} ingredients={p.ingredients} calc={p.recheioCalc}/></div>}
function Assembly({assembly,setAssembly,ingredients,caldaCalc,recheioCalc,final}){const upd=(i,k,v)=>setAssembly(assembly.map((r,idx)=>idx===i?{...r,[k]:k==='percent'?n(v):v}:r)); const components=['Calda Base','Recheio',...ingredients.map(i=>i.name)]; return <section className="panel"><div className="toolbar"><h2>Composição do produto final</h2><button className="primary" onClick={()=>setAssembly([...assembly,{component:'Calda Base',type:'AGREGADO',percent:0}])}><Plus size={16}/>Adicionar</button></div><table><thead><tr><th>Componente pesquisável</th><th>Tipo</th><th>% produto</th><th>kcal final</th><th>Carb</th><th>Aç. adic.</th><th>Gord.</th><th></th></tr></thead><tbody>{assembly.map((r,i)=>{const vals=rowFinal(r,caldaCalc,recheioCalc,ingredients); return <tr><td><input list="componentes" value={r.component} onChange={e=>upd(i,'component',e.target.value)}/><datalist id="componentes">{components.map(c=><option value={c}/>)}</datalist></td><td><select value={r.type} onChange={e=>upd(i,'type',e.target.value)}>{['CALDA','RECHEIO','AGREGADO'].map(t=><option>{t}</option>)}</select></td><td><input type="number" value={r.percent} onChange={e=>upd(i,'percent',e.target.value)}/></td><td>{fmt(vals.kcal,1)}</td><td>{fmt(vals.carb,1)}</td><td>{fmt(vals.addedSugars,1)}</td><td>{fmt(vals.fat,1)}</td><td><button className="icon" onClick={()=>setAssembly(assembly.filter((_,idx)=>idx!==i))}><Trash2 size={16}/></button></td></tr>})}</tbody></table><div className="mini"><b>Produto final / 100 g:</b> {fmt(final.kcal,1)} kcal • {fmt(final.carb,1)} g carboidratos • {fmt(final.addedSugars,1)} g açúcares adicionados • {fmt(final.sodium,0)} mg sódio</div></section>}
function Label({product,portion,house,pack,final,warnings}){const rows=[['Valor energético','kcal','kcal'],['Carboidratos','carb','g'],['Açúcares totais','sugars','g'],['Açúcares adicionados','addedSugars','g'],['Proteínas','protein','g'],['Gorduras totais','fat','g'],['Gorduras saturadas','satFat','g'],['Gorduras trans','transFat','g'],['Fibra alimentar','fiber','g'],['Sódio','sodium','mg']]; return <section className="labelbox"><div className="ft"><h2>INFORMAÇÃO NUTRICIONAL</h2><p>Porções por embalagem: {pack}</p><p>Porção: {portion} g ({house})</p><table><thead><tr><th></th><th>100 g</th><th>{portion} g</th><th>%VD*</th></tr></thead><tbody>{rows.map(([label,k,unit])=>{let v100=final[k], vp=v100*portion/100, pct=vd(k,vp);return <tr><td>{label} ({unit})</td><td>{roundLabel(k,v100)}</td><td>{roundLabel(k,vp)}</td><td>{pct==null?'-':Math.round(pct)+'%'}</td></tr>})}</tbody></table><p className="small">*Percentual de valores diários fornecidos pela porção.</p></div><div className="front"><h2>Rotulagem frontal</h2>{warnings.length?warnings.map(w=><div className="lupa big">{w}</div>):<div className="success">Sem lupa para os limites avaliados.</div>}<h3>Lista de ingredientes</h3><p>Próxima etapa: ordenar por predominância, subingredientes, alergênicos, glúten e lactose.</p></div></section>}
function Alerts({final}){return <section className="panel"><h2>Check automático para rotulagem frontal — por 100 g</h2><table><thead><tr><th>Nutriente</th><th>Resultado</th><th>Limite interno</th><th>Parecer</th></tr></thead><tbody><tr><td>Açúcares adicionados</td><td>{fmt(final.addedSugars,1)} g/100g</td><td>≥ 15 g/100g</td><td>{final.addedSugars>=15?'ALTO EM AÇÚCAR ADICIONADO':'Não atinge limite'}</td></tr><tr><td>Gorduras saturadas</td><td>{fmt(final.satFat,1)} g/100g</td><td>≥ 6 g/100g</td><td>{final.satFat>=6?'ALTO EM GORDURA SATURADA':'Não atinge limite'}</td></tr><tr><td>Sódio</td><td>{fmt(final.sodium,0)} mg/100g</td><td>≥ 600 mg/100g</td><td>{final.sodium>=600?'ALTO EM SÓDIO':'Não atinge limite'}</td></tr></tbody></table><p className="note">Os limites estão estruturados para pré-check de sólidos/semissólidos. Valide enquadramento do produto e arte final com o RT.</p></section>}
function Input({label,value,onChange,type='text'}){return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
createRoot(document.getElementById('root')).render(<App/>);
